Updated admin-www-logrotate to use config file.

diff --git a/bin/admin-www-logrotate b/bin/admin-www-logrotate
--- a/bin/admin-www-logrotate
+++ b/bin/admin-www-logrotate
@@ -1,40 +1,49 @@
-#!/bin/sh
+#!/usr/bin/env bash
+#
+# Rotates HTTP access log files.
+#
+# Syntax: admin-www-logrotate [-v]
+#
+# Files:
+#   /etc/admin-www-logrotate.conf
+#
 
 # Configuration variables
-LOG_DIR=/var/log/***
-STAT_DIR=***/logstats
+CONFIG=/etc/admin-www-logrotate.conf
+LOCALDIR=`dirname $0`/..
 VERBOSE="false"
 
-# Function for printing command-line help
-printhelp() {
-    ERROR=$1
-    echo "Rotates the Nginx log files."
-    echo
-    echo "Syntax: admin-logrotate [-v]"
-    echo
-    echo "Options:"
-    echo "  -v  Print verbose output."
-    if [ "$ERROR" != "" ] ; then
-        echo
-        echo "ERROR: $ERROR" >&2
-    fi
+# Set caution flags
+set -o nounset
+set -o errtrace
+set -o errexit
+set -o pipefail
+
+# Function for logging an error to stderr and exiting
+fail() {
+    echo "ERROR:" $* >&2
+    exit 1
 }
 
-# Function for printing verbose information
-printinfo() {
-    if [ $VERBOSE = "true" ] ; then
-        echo `date +"%F %T"`: $*
-    fi
+# Function for logging information in verbose mode
+log() {
+    [ "$VERBOSE" = "true" ] && echo `date +"%F %T"`: $*
 }
 
 # Check for root user
-if [ `whoami` != 'root' ] ; then
-    echo "ERROR: only root is allowed to run administration tasks" >&2
-    exit 1
+[ `whoami` == 'root' ] || fail "only root is allowed to run admin-www-logrotate"
+
+# Load config (shell)
+if [ -f $CONFIG ] ; then
+    . $CONFIG
+elif [ -f $LOCALDIR/$CONFIG ] ; then
+    . $LOCALDIR/$CONFIG
+else
+    fail "missing config file $CONFIG"
 fi
 
 # Parse command-line arguments
-if [ "$1" = "-v" ] ; then
+if [ "${1:-}" = "-v" ] ; then
     shift
     VERBOSE=true
 fi
@@ -44,38 +53,39 @@ YESTERDAY=`date -d "-1 day" +%Y%m%d`
 FILES=`find $LOG_DIR -name '*.log'`
 for LOG in $FILES ; do
     if [ -e $LOG.$YESTERDAY -o -e $LOG.$YESTERDAY.lzma ] ; then
-        printinfo skipping $LOG "(already rotated)"
+        log "skipping $LOG (already rotated)"
     else
-        printinfo rotating $LOG
+        log "rotating $LOG"
         mv $LOG $LOG.$YESTERDAY
     fi
 done
 
 # Restart Nginx to create new logs
-printinfo restarting Nginx
-[ -f /var/run/nginx.pid ] && kill -USR1 `cat /var/run/nginx.pid`
-printinfo sleeping 60 seconds
+log "running $COMMAND"
+$COMMAND
+log "sleeping 60 seconds"
 sleep 60
-
-# Process web statistics
-LOG_FILE=$LOG_DIR/access.log.$YESTERDAY
-JSON_FILE=$STAT_DIR/logstats.$YESTERDAY.json
-TEXT_FILE=$STAT_DIR/logstats.$YESTERDAY.txt
-printinfo processing stats on $LOG_FILE
-/usr/local/bin/admin-webstats --json $JSON_FILE --text $TEXT_FILE $LOG_FILE
 
 # Compress rotated log files
 for LOG in $FILES ; do
     if [ -s $LOG.$YESTERDAY ] ; then
-        printinfo compressing $LOG.$YESTERDAY
+        log "compressing $LOG.$YESTERDAY"
         lzma $LOG.$YESTERDAY
     else
-        printinfo removing empty file $LOG.$YESTERDAY
+        log "removing empty file $LOG.$YESTERDAY"
         rm -f $LOG.$YESTERDAY
     fi
 done
 
 # Remove old log files
-printinfo removing old log files
-find $LOG_DIR -name '*.gz' -mtime +30 | xargs -r rm
-find $LOG_DIR -name '*.lzma' -mtime +30 | xargs -r rm
+log "removing old log files"
+find $LOG_DIR -name '*.gz' -mtime +$LOG_EXPIRES -exec rm -rf {} \;
+find $LOG_DIR -name '*.lzma' -mtime +$LOG_EXPIRES -exec rm -rf {} \;
+
+# Process web statistics
+LOG_FILES=`find $LOG_DIR -name 'access.log.$YESTERDAY.lzma'`
+JSON_FILE=$STAT_DIR/logstats.$YESTERDAY.json
+TEXT_FILE=$STAT_DIR/logstats.$YESTERDAY.txt
+log "processing stats to $STAT_DIR"
+/usr/local/bin/admin-webstats --json $JSON_FILE --text $TEXT_FILE $LOG_FILES
+/usr/local/bin/admin-freemem
