Updated admin-uptodate to bash.

diff --git a/bin/admin-uptodate b/bin/admin-uptodate
--- a/bin/admin-uptodate
+++ b/bin/admin-uptodate
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/usr/bin/env bash
 #
 # Runs a check to determine if the system requires updates.
 #
@@ -10,45 +10,55 @@
 #
 
 # Configuration parameters
+HOST=`hostname --fqdn`
 SENDMAIL=/usr/sbin/sendmail
 SECURITY=false
 MAIL=false
 
-# Check for root user
-if [ `whoami` != 'root' ] ; then
-    echo "ERROR: Only root is allowed to run admin-uptodate" >&2
+# Set caution flags
+set -o nounset
+set -o errtrace
+set -o errexit
+set -o pipefail
+
+# Function for logging an error to stderr and exiting
+fail() {
+    echo "ERROR:" $* >&2
     exit 1
-fi
+}
+
+# Check for root user
+[ `whoami` == 'root' ] || fail "only root is allowed to run admin-uptodate"
 
 # Parse command-line arguments
-if [ "$1" = "-s" ] ; then
+if [ "${1:-}" == "-s" ] ; then
     shift
     SECURITY=true
 fi
-if [ "$1" = "-m" ] ; then
+if [ "${1:-}" == "-m" ] ; then
     shift
     MAIL=true
 fi
 
 # Check for update
-apt-get update > /dev/null
+apt-get update > /dev/null || fail "couldn't update package lists with apt-get"
 OUTFILE=/tmp/admin-uptodate.txt
-echo "Subject: System updates available for `hostname`" > $OUTFILE
-echo >> $OUTFILE
-apt-get --simulate --quiet upgrade >> $OUTFILE
-if [ "$SECURITY" = "true" ] ; then
-    RESULT=`grep "security" $OUTFILE`
-elif [ -z "`grep "0 upgraded" $OUTFILE`" ] ; then
-    RESULT="true"
+apt-get --simulate --quiet upgrade > $OUTFILE || fail "couldn't simulate package upgrade"
+if [ "$SECURITY" == "true" ] ; then
+    TYPE="security updates"
+    FOUND=`grep "Inst " $OUTFILE | grep -c "security"` || true
 else
-    RESULT=""
+    TYPE="updates"
+    FOUND=`grep -c "Inst " $OUTFILE` || true
 fi
-if [ -n "$RESULT" ] ; then
-    if [ "$MAIL" = "true" ] ; then
-        cat $OUTFILE | $SENDMAIL root
+if [ $FOUND -ne 0 ] ; then
+    if [ $MAIL == "true" ] ; then
+        printf "Subject: System $TYPE for $HOST\n\n" > $OUTFILE.1
+        printf "Found $FOUND system $TYPE for $HOST:\n\n" > $OUTFILE.2
+        cat $OUTFILE.1 $OUTFILE.2 $OUTFILE | $SENDMAIL root
+        rm $OUTFILE.1 $OUTFILE.2
     else
-        echo "Updates available:"
-        echo
+        printf "Found $FOUND system $TYPE for $HOST:\n\n"
         cat $OUTFILE
     fi
 fi
