Updated admin-restart to support terminal colors and replaced alert with warn.

diff --git a/bin/admin-restart b/bin/admin-restart
--- a/bin/admin-restart
+++ b/bin/admin-restart
@@ -19,14 +19,28 @@ set -o errtrace
 set -o errexit
 set -o pipefail
 
-# Function for logging an error to stderr without exiting
-alert() {
-    echo "ALERT:" "$*" >&2
+# Setup color codes
+case $TERM in
+    *color)
+        COLOR_OFF=`echo -en '\033[0m'`
+        COLOR_OK=`echo -en '\033[32m'`
+        COLOR_ERR=`echo -en '\033[1;31m'`
+        ;;
+    *)
+        COLOR_OFF=''
+        COLOR_OK=''
+        COLOR_ERR=''
+        ;;
+esac
+
+# Function for logging a warning to stderr without exiting
+warn() {
+    echo "${COLOR_ERR}WARNING:${COLOR_OFF}" "$*" >&2
 }
 
 # Function for logging an error to stderr and exiting
 fail() {
-    echo "ERROR:" "$*" >&2
+    echo "${COLOR_ERR}ERROR:${COLOR_OFF}" "$*" >&2
     exit 1
 }
 
@@ -107,12 +121,12 @@ stop() {
     if [ "$WAIT" != "" -a "$PID" != "" ] ; then
         waitprocess $WAIT $PID
         if [ "$FORCE" != "" ] && ps --pid $PID > /dev/null ; then
-            alert "sending TERM signal to $NAME (pid: $PID)..."
+            warn "sending TERM signal to $NAME (pid: $PID)..."
             kill -TERM $PID
             waitprocess $WAIT $PID
         fi
         if [ "$FORCE" != "" ] && ps --pid $PID > /dev/null ; then
-            alert "sending KILL signal to $NAME (pid: $PID)..."
+            warn "sending KILL signal to $NAME (pid: $PID)..."
             kill -KILL $PID
             waitprocess $WAIT $PID
         fi
