Changed to $@ instead of $* in shell functions.

diff --git a/bin/simple-fileinfo b/bin/simple-fileinfo
--- a/bin/simple-fileinfo
+++ b/bin/simple-fileinfo
@@ -21,7 +21,7 @@ usage() {
 
 # Function for logging an error to stderr and exiting
 fail() {
-    echo "ERROR:" "$*" >&2
+    echo "ERROR:" "$@" >&2
     exit 1
 }
 
diff --git a/bin/simple-restart b/bin/simple-restart
--- a/bin/simple-restart
+++ b/bin/simple-restart
@@ -29,18 +29,18 @@ COLOR_ERR=`tput setaf 1; tput bold`
 
 # Function for logging a warning to stderr without exiting
 warn() {
-    echo "${COLOR_ERR}WARNING:${COLOR_OFF}" "$*" >&2
+    echo "${COLOR_ERR}WARNING:${COLOR_OFF}" "$@" >&2
 }
 
 # Function for logging an error to stderr and exiting
 fail() {
-    echo "${COLOR_ERR}ERROR:${COLOR_OFF}" "$*" >&2
+    echo "${COLOR_ERR}ERROR:${COLOR_OFF}" "$@" >&2
     exit 1
 }
 
 # Function for logging information in verbose mode
 log() {
-    [ "$VERBOSE" == "true" ] && echo `date +"%F %T"`: "$*" || true
+    [ "$VERBOSE" == "true" ] && echo `date +"%F %T"`: "$@" || true
 }
 
 # Function for printing command-line usage info
diff --git a/bin/simple-status b/bin/simple-status
--- a/bin/simple-status
+++ b/bin/simple-status
@@ -27,12 +27,12 @@ COLOR_ERR=`tput setaf 1; tput bold`
 
 # Function for logging a warning to stderr without exiting
 warn() {
-    echo "${COLOR_ERR}WARNING:${COLOR_OFF}" "$*" >&2
+    echo "${COLOR_ERR}WARNING:${COLOR_OFF}" "$@" >&2
 }
 
 # Function for logging an error to stderr and exiting
 fail() {
-    echo "${COLOR_ERR}ERROR:${COLOR_OFF}" "$*" >&2
+    echo "${COLOR_ERR}ERROR:${COLOR_OFF}" "$@" >&2
     exit 1
 }
 
diff --git a/bin/simple-www-webalizer b/bin/simple-www-webalizer
--- a/bin/simple-www-webalizer
+++ b/bin/simple-www-webalizer
@@ -21,13 +21,13 @@ set -o pipefail
 
 # Function for logging an error to stderr and exiting
 fail() {
-    echo "ERROR:" "$*" >&2
+    echo "ERROR:" "$@" >&2
     exit 1
 }
 
 # Function for logging information in verbose mode
 log() {
-    [ "$VERBOSE" == "true" ] && echo `date +"%F %T"`: "$*" || true
+    [ "$VERBOSE" == "true" ] && echo `date +"%F %T"`: "$@" || true
 }
 
 # Load config (shell)
